### ISSUE TITLE
Documentation mention NServiceBusDistributedEventBrokerExtension

### ISSUE THREAD

**Issue by jho1965us** [appccelerate/distributedeventbroker.nservicebus#1]
But that class seems to be only in the old repository (appccelerate/appccelerate) not in the new (appccelerate/distributedeventbroker.nservicebus)

**Comment by ursenzler** [comment]
Hmm, I'll have to check why the class is missing. it probably got lost during migration into its own repository.

**Comment by ursenzler** [comment]
I have added the missing file and made a new release (2.8.0)

Thanks!
